# frozen_string_literal: true

source 'https://rubygems.org'

gem 'middleman', '~> 4.5'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'terser', '~> 1.1'
gem 'tzinfo-data', platforms: %i[mswin mingw jruby x64_mingw]
gem 'wdm', '~> 0.1', platforms: %i[mswin mingw x64_mingw]

gem 'middleman-importmap', path: '../../'
